name: Build and deploy

on:
  push:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Build version
      run: |
        BUILD_VERSION=1.0.$(date +%y%j)-$(date +%H%M)
        DOCKER_IMAGE_NAME=${{ vars.ACR_LOGIN_SERVER }}/${{ vars.AZURE_WEBAPP_NAME }}
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@main
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install     

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - run: |
        DOCKER_IMAGE_TAG_VERSIONED=$DOCKER_IMAGE_NAME:$BUILD_VERSION
        DOCKER_IMAGE_TAG_LATEST=$DOCKER_IMAGE_NAME:latest
        docker build . --tag $DOCKER_IMAGE_TAG_VERSIONED --tag $DOCKER_IMAGE_TAG_LATEST --build-arg BUILD_VERSION=$BUILD_VERSION
        docker push $DOCKER_IMAGE_TAG_VERSIONED
        docker push $DOCKER_IMAGE_TAG_LATEST
